#!/bin/bash

# adjust sleep seconds to your particular linux server needs
sleep 15
nohup x3270 -port 3270 -model 3279-3 127.0.0.1 > /dev/null 2>&1 &
sleep 2
nohup x3270 -port 3270 -model 3279-3 127.0.0.1 > /dev/null 2>&1 &


